server:
  port: 3899
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yan_blog?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 806312
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  data:
    redis:
      port: 6379
      password: redispassword
      host: 192.168.25.129
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
